# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build iOS app"
  lane :build do
    build_app(
      scheme: "PostsApp",
      destination: "platform=iOS Simulator,name=iPhone 15 Pro",
      configuration: "Debug",
      include_bitcode: false
    )
  end

  desc "Run tests"
  lane :test do
    run_tests(
      devices: ["iPhone 15 Pro"],
      scheme: "PostsApp",
      skip_build: true
    )
  end
end
