name: GitHub Action 

on: 
  push:
    branches:    
      - dev
  pull_request:
    branches:    
      - main

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Cleanup
        run: |
          xcodebuild clean -project PostsApp.xcodeproj -scheme PostApp | xcpretty
          
      - name: Test
        run: |
          xcodebuild test -project PostsApp.xcodeproj -scheme PostsApp -destination 'platform=iOS   Simulator,name=iPhone 15' | xcpretty -s
