name: Unit Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    name: Tests
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app
          
      - name: Test
        run: bundle exec fastlane test
