name: Unit Test

on:
  pull_request:

jobs:
  deploy:
    name: Tests
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Cleanup
        run: |
          xcodebuild clean -project PostsApp.xcodeproj -scheme PostsApp | xcpretty
          
      - name: Test
        run: |
          xcodebuild test -project PostsApp.xcodeproj -scheme PostsApp -destination 'platform=iOS Simulator,name=iPhone 15 Pro' | xcpretty -s || exit 1
